### ISSUE TITLE
Website Broken

### ISSUE THREAD

**Issue by tjlauer** [front/create-cloud-block#6]
The listed website [`gutenbergcloud.org`](https://gutenbergcloud.org/) seems to be broken.

1. The SSL certificate is expired
2. The landing page displays `Passenger error #3`
![image](https://github.com/front/create-cloud-block/assets/25645380/af68877e-0aaf-4e9c-b5b7-38798ae7fa3f)

**Comment by eiriksm** [comment]
https://gutenbergcloud.org/ was decided to be shut down.

I will remember to get back here and link a more formal notice if it gets created :v:
